### ISSUE TITLE
hello..u write C#..code,too. so can connect u ths

### ISSUE THREAD

**Issue by AtlantisDe** [bigsinger/TextFormater#1]
### hello..u write C#..code,too. so can connect u ?ths

```c#
if can it, i will send the mail....to u
```

**Comment by bigsinger** [comment]
> ### hello..u write C#..code,too. so can connect u ?ths
> ```cs
> if can it, i will send the mail....to u
> ```

yes

**Comment by AtlantisDe** [comment]
hi
